### ISSUE TITLE
Show cluster names to the user when running E2E test

### ISSUE THREAD

**Issue by karuppiah7890** [karuppiah7890/tce-e2e-test#33]
We can show bootstrap cluster, management cluster, and workload cluster names when running E2E tests so that the user knows what to look for etc

**Comment by mohitsharma-in** [comment]
[Fixed in commit](https://github.com/karuppiah7890/tce-e2e-test/tree/ce957a9d6b6ea4f9ad98011ba5c1b4043575eb4f )
